version: '3.3'

services:
  web:
    image: mysonet-php:test
    volumes:
      - ./mysonet-data:/var/www/html
      - /home/mysonet/sshkey:/root/.ssh:ro
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mariadb:10.11.4
    restart: always
    volumes:
      - ./mysonet-mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123456a.
      - MARIADB_DATABASE=mysonet
      - MARIADB_USER=mysonet
      - MARIADB_PASSWORD=123456a.
